server:
  port: 8191
  
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
#    username: root
#    password: 1qaz2wsx@
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#
##  jpa:
##    hibernate:
##      ddl-auto: none #create
##    show-sql: true
##
##logging:
##  level:
##    org:
##      hibernate:
##        type: trace
#
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace